### ISSUE TITLE
请问路径分隔符，能否支持自定义？

### ISSUE THREAD

**Issue by ztj1993** [gookit/config#11]
假设 key 存在 `.` 符号，是否会存在误区，分隔符能否自定义？假设 key 中存在域名怎么办？

若能自定义分隔符，是否可以 map 多维到一维互转？

准备用 go 做一个开源程序，主要涉及 json yaml ini 这一块。
需要实现一个支持将多维扁平化处理，将一维多维处理。

**Comment by inhere** [comment]
可以自定义分隔符 https://github.com/gookit/config/issues/10#issuecomment-524509067

**Comment by inhere** [comment]
可以满足你的需求吗？我先关了，有问题你再打开。

**Comment by ztj1993** [comment]
@inhere 可以满足需求，但因为时间关系，最终我的开源项目采用 python 做了  /(ㄒoㄒ)/~~

**Comment by inhere** [comment]
😄 嗯。对 py 不是太了解。
