### ISSUE TITLE
如何在config中删除一个key

### ISSUE THREAD

**Issue by LKKlein** [gookit/config#12]
想问一下，有没有办法可以直接在`config`中，根据给定的路径，删除对应的`key`

**Comment by inhere** [comment]
:( 为啥要这样操作配置呢

**Comment by LKKlein** [comment]
额，开始是用来读写配置文件的，后面发现操作`json`也很方便，就直接用来管理`json`了。
这里主要是为了删除数据传递过程中的一些中间变量，比如图片的base64值。

**Comment by inhere** [comment]
... 你直接设置为 `some.key=nil` 呢
