### ISSUE TITLE
结构体中包含数组字段，数组中的子结构体字段设置默认值不生效。

### ISSUE THREAD

**Issue by ansoda** [gookit/config#141]

**Comment by inhere** [comment]
可以给个结构体示例吗

**Comment by ansoda** [comment]
![image](https://github.com/gookit/config/assets/5748600/5200e9ef-67bf-467a-b608-05ea1793e1cb)
当配置多个Logger时，Logger中的默认值不生效

**Comment by inhere** [comment]
已增强处理，下个版本支持。

**Comment by ansoda** [comment]
示例config.json


      {
        "loggers": [
          {
            "name": "info",
            "logFile": "logs/info.log"
          },
          {
            "name": "error",
            "logFile": "logs/error.log"
          },
          {
            "name": "request",
            "logFile": "logs/request.log",
            "maxSize": 2048,
            "maxDays": 30,
            "compress": false
          }
        ]
      }

通过如上的config.json测试不通过。
当数组中超过2个结构体需要默认值时，只有第一个结构体被赋了默认值，后面的结构体没有赋默认值。

@inhere

**Comment by ansoda** [comment]
> 已增强处理，下个版本支持。
> 
> ## 测试示例
> 示例 config.json:
> 
> ```json
> {
> 	"loggers": [
> 		{
> 			"name": "error",
> 			"logFile": "logs/error.log"
> 		},
> 		{	
> 			"name": "request",
> 			"logFile": "logs/request.log",
> 			"maxSize": 2048,
> 			"maxDays": 30,
> 			"compress": false
> 		}
> 	]
> }
> ```
> 
> ```go
> 	type Logger struct {
> 		Name     string `json:"name"`
> 		LogFile  string `json:"logFile"`
> 		MaxSize  int    `json:"maxSize" default:"1024"` // MB
> 		MaxDays  int    `json:"maxDays" default:"7"`
> 		Compress bool   `json:"compress" default:"true"`
> 	}
> 
> 	type LogConfig struct {
> 		Loggers []*Logger `default:""` // mark for parse default
> 	}
> 
> 	c := config.New("issues141", config.ParseDefault)
> 	c.LoadFiles("config.json")
> 
> 	opt := &LogConfig{}
> 	err = c.Decode(opt)
> 	dump.Println(opt)
> ```
> 
> 输出效果：
> 
> ```go
> === RUN   TestIssues_141
> PRINT AT github.com/gookit/config/v2_test.TestIssues_141(issues_test.go:348)
> &config_test.LogConfig {
>   Loggers: []*config_test.Logger [ #len=2,cap=2
>     &config_test.Logger {
>       Name: string("error"), #len=5
>       LogFile: string("logs/error.log"), #len=14
>       MaxSize: int(1024),
>       MaxDays: int(7),
>       Compress: bool(true),
>     },
>     &config_test.Logger {
>       Name: string("request"), #len=7
>       LogFile: string("logs/request.log"), #len=16
>       MaxSize: int(2048),
>       MaxDays: int(30),
>       Compress: bool(false),
>     },
>   ],
> },
> --- PASS: TestIssues_141 (0.00s)
> PASS
> ```

@inhere

**Comment by ansoda** [comment]
> 示例config.json
> 
> ```
>   {
>     "loggers": [
>       {
>         "name": "info",
>         "logFile": "logs/info.log"
>       },
>       {
>         "name": "error",
>         "logFile": "logs/error.log"
>       },
>       {
>         "name": "request",
>         "logFile": "logs/request.log",
>         "maxSize": 2048,
>         "maxDays": 30,
>         "compress": false
>       }
>     ]
>   }
> ```
> 
> 通过如上的config.json测试不通过。 当数组中超过2个结构体需要默认值时，只有第一个结构体被赋了默认值，后面的结构体没有赋默认值。
> 
> @inhere

示例config.json

    {
      "loggers": [
        {
          "name": "info",
          "logFile": "logs/info.log"
        },
        {
          "name": "error",
          "logFile": "logs/error.log"
        },
        {
          "name": "request",
          "logFile": "logs/request.log",
          "maxSize": 2048,
          "maxDays": 30,
          "compress": false
        }
      ]
    }
通过如上的config.json测试不通过。
当数组中超过2个结构体需要默认值时，只有第一个结构体被赋了默认值，后面的结构体没有赋默认值。

@inhere

**Comment by ansoda** [comment]
> 已增强处理，下个版本支持。
> 
> ## 测试示例
> 示例 config.json:
> 
> ```json
> {
> 	"loggers": [
> 		{
> 			"name": "error",
> 			"logFile": "logs/error.log"
> 		},
> 		{	
> 			"name": "request",
> 			"logFile": "logs/request.log",
> 			"maxSize": 2048,
> 			"maxDays": 30,
> 			"compress": false
> 		}
> 	]
> }
> ```
> 
> ```go
> 	type Logger struct {
> 		Name     string `json:"name"`
> 		LogFile  string `json:"logFile"`
> 		MaxSize  int    `json:"maxSize" default:"1024"` // MB
> 		MaxDays  int    `json:"maxDays" default:"7"`
> 		Compress bool   `json:"compress" default:"true"`
> 	}
> 
> 	type LogConfig struct {
> 		Loggers []*Logger `default:""` // mark for parse default
> 	}
> 
> 	c := config.New("issues141", config.ParseDefault)
> 	c.LoadFiles("config.json")
> 
> 	opt := &LogConfig{}
> 	err = c.Decode(opt)
> 	dump.Println(opt)
> ```
> 
> 输出效果：
> 
> ```go
> === RUN   TestIssues_141
> PRINT AT github.com/gookit/config/v2_test.TestIssues_141(issues_test.go:348)
> &config_test.LogConfig {
>   Loggers: []*config_test.Logger [ #len=2,cap=2
>     &config_test.Logger {
>       Name: string("error"), #len=5
>       LogFile: string("logs/error.log"), #len=14
>       MaxSize: int(1024),
>       MaxDays: int(7),
>       Compress: bool(true),
>     },
>     &config_test.Logger {
>       Name: string("request"), #len=7
>       LogFile: string("logs/request.log"), #len=16
>       MaxSize: int(2048),
>       MaxDays: int(30),
>       Compress: bool(false),
>     },
>   ],
> },
> --- PASS: TestIssues_141 (0.00s)
> PASS
> ```

示例config.json

    {
      "loggers": [
        {
          "name": "info",
          "logFile": "logs/info.log"
        },
        {
          "name": "error",
          "logFile": "logs/error.log"
        },
        {
          "name": "request",
          "logFile": "logs/request.log",
          "maxSize": 2048,
          "maxDays": 30,
          "compress": false
        }
      ]
    }
通过如上的config.json测试不通过。
当数组中超过2个结构体需要默认值时，只有第一个结构体被赋了默认值，后面的结构体没有赋默认值。

@inhere

**Comment by inhere** [comment]
Thanks @ansoda , 本地再调整了下逻辑，先映射配置在做初始化可以解决。

但是有个问题：
 bool字段 你配置了 false，也会被初始化为 default:"true"。因为 bool(false) 是零值，会认为是没有设置过。

> Compress bool   `json:"compress" default:"true"`

**Comment by ansoda** [comment]
> 

针对bool类型配置中已经被设置了false，最后结构体还是被置成true的问题。主要是把字段未设置和字段值为false没有区别对待了。不知道这种情况，有没有更好办法应对？

**Comment by inhere** [comment]
这是go本身的性质，无法区分。 就跟 `int` 字段设置个 0，你也不知道是go初始化的还是外部设置的。
