### ISSUE TITLE
LoadFromDir 返回类型

### ISSUE THREAD

**Issue by zuozhehao** [gookit/config#173]
```
var data []*Data
config.Decode(&data)
```
返回的是map[string]*Data，不是[]*Data

**Comment by inhere** [comment]
能具体描述下吗？`LoadFromDir` 会用 文件名作为文件内容的 key (eg: `path/to/dir/task.json => task`)

**Comment by inhere** [comment]
这样就完全没法取指定文件的配置了，跟平常的用法有点区别了。

**Comment by zuozhehao** [comment]
> 这样就完全没法取指定文件的配置了，跟平常的用法有点区别了。

嗯，能否返回的时候做处理。

**Comment by inhere** [comment]
config 底层的 data 始终需要一个 key 存数据

--------

`LoadFromDir(dirPath, format string)` 我可以新增个参数 `dataKey`：

```go
LoadFromDir(dirPath, format string, dataKey string)
```

- dataKey 默认 "" 使用文件名作为文件内容的key
- dataKey="somekey" 设置key,搜集所有的文件内容塞到这个key 里组成slice. `{somekey: [{file1 data}, {file2 data}, ...]}`

### decode 数据：

```go
var data []*Data
config.MapStruct("somekey", &data)
```

**Comment by inhere** [comment]
可以升级到 https://github.com/gookit/config/releases/tag/v2.2.5 试试
