### ISSUE TITLE
Add http://  Support

### ISSUE THREAD

**Issue by zhangjinming** [gookit/config#2]
"address": [
			"192.168.1.XXX:2379",
			"192.168.1.XXX:2379",
			"192.168.1.XXX:2379"
		]
is OK, but
		"address": [
			"http://192.168.1.XXX:2379",
			"http://192.168.1.XXX:2379",
			"http://192.168.1.XXX:2379"
		]
is panic.
panic: ReadString: invalid control character found: 10, error found in #10 byte of ...|79"
Strings containing “http://” are very common, Don't be confused with comments。
Tanks.

**Comment by inhere** [comment]
is JSON data?

please provides some demo code :)

**Comment by inhere** [comment]
fixed, please update it.
