### ISSUE TITLE
Regression in yml file support introduced

### ISSUE THREAD

**Issue by vthiery** [gookit/config#35]
**System:**

 - OS: `linux`
 - GO Version: `1.15.6` 
 - Pkg Version: `2.0.19` 

**Describe the bug**

This [change](https://github.com/gookit/config/commit/8712ba0bbdc211b96abe45a761567151acad5ab5#diff-403796dafb14f72be4282f434fde401adb53fc36666b7bdec721f35e13a45fde) (see #30) introduced a regression in the supported file types. Before that, the function `LoadFiles` supported `yaml` **and** `.yml` extensions after loading the `yaml.Driver` driver.

**To Reproduce**

```go
AddDriver(yaml.Driver)
...
LoadFiles("file.yml")
..
```

**Expected behavior**

I expect that once the `yaml.Driver` is loaded, both `.yaml` and `.yml` files are supported.

**Comment by inhere** [comment]
@vthiery thanks.

fixed. release the `v2.0.20`

**Comment by vthiery** [comment]
> @vthiery thanks.
> 
> fixed. release the `v2.0.20`

Thanks a lot for the quick fix!
