### ISSUE TITLE
文件名后缀作为判断依据的问题

### ISSUE THREAD

**Issue by yuechao-zhao** [gookit/config#58]
对于一些工具的配置文件，格式虽然可能是ini，yaml或者json
但是为了区分这些文件的作用，可能不再是ini，yaml这样的后缀，
而是会以rules，system这样的后缀结尾，
而我看你的parseSourceCode()中会检查这样的后缀，作为文件格式的判断依据
但是对于上述描述到的文件，就会被认定为不合法的文件格式，

对于这样的情况能否给个方法，可以让我直接指定文件格式，从而解决这样的问题呢？

**Comment by inhere** [comment]
可以加个 `LoadFilesWithFormat()`. 
 
现在的话你可以自己读取文件内容，再通过 `LoadStrings` `LoadSources` 读取内容到config. 这两个方法可以指定 format

**Comment by yuechao-zhao** [comment]
好的，多谢

**Comment by inhere** [comment]
你一般是用 `LoadFiles` 还是 `LoadExists`

**Comment by inhere** [comment]
> 我都可以用，这个无所谓的，你如何提供API，我就按照你的要求使用便可

`v2.0.26` 已经新增了 `LoadFilesByFormat` `LoadExistsByFormat` 方法

**Comment by yuechao-zhao** [comment]
嗯 我已经开始使用了
