### ISSUE TITLE
Actual v2.0.6 release file has incorrect ini version

### ISSUE THREAD

**Issue by MostHated** [gookit/config#6]
Hey there,
    I have been fighting with this for longer than I care to admit when I finally realized that when my project tries to download v2.0.6 it has the incorrect ini version. Your go.mod in the repo is correct but if you download v2.0.6 from the release tab, ini has v1 instead of v2 as you can see highlighted below.

![](https://i.imgur.com/GtealYu.png)

Thanks,
-MH

**Comment by inhere** [comment]
Thanks for the tip 😄
