### ISSUE TITLE
如何实现自动保存，或者set回调以实现自动保存

### ISSUE THREAD

**Issue by aadog** [gookit/config#61]
如何实现自动保存，或者set回调以实现自动保存

**Comment by a97077088** [comment]
大部分情况下都需要可写 有一个onset回调来写回缓存并保存文件 这个库实现很完美 唯独缺了这个 如果有手动保存模式和自动保存模式很好 单独的write太过繁琐了

**Comment by a97077088** [comment]
它有任何进度吗，或者需要我帮住吗，我也可以提交

**Comment by inhere** [comment]
暂时没有时间改进这个。你能发个PR最好了 👍

**Comment by inhere** [comment]
添加了一个简单的事件触发。可以看看：

**Comment by aadog** [comment]
thanks
