### ISSUE TITLE
How to parse ini to struct if data within [brackets] is variable?

### ISSUE THREAD

**Issue by MostHated** [gookit/config#7]
Hello,
    I was wondering how I might go about parsing to a struct a file like below:

```ini
[variablename1]
type = 
client_id = 
client_secret = 
scope = 
token = 

```

[variablename1] will always be unique as it is a name assigned at the time of creation of the ini, the rest of the fields will always have the same key name.

I was going to have:

```Go
type Settings struct {
	Remote struct {
		Type         string `json:"type"`
		ClientId     string `json:"client_id"`
		ClientSecret string `json:"client_secret"`
		Scope        int    `json:"scope"`
		Token        int    `json:"token"`
	} `json:"???"` // --- This will always be different
}

```

Is there a way to deal with this?
Thanks,
-MH

**Comment by inhere** [comment]
Oo, why use this?

**Comment by MostHated** [comment]
Well, I was going to use it to parse the config file for RClone backup tool's config data, but instead I just ended up looking through their code to see how they were getting the data themselves and did it using the same method they did. I don't really like the method as much, but it worked, so it's ok, no need for this question anymore.

**Comment by inhere** [comment]
If you know the variable name when you use it. Can be taken directly like this:

```go
Remote.Type = config.String("VARNAME.type")
Remote.ClientId = config.String("VARNAME.client_id")
...
```

**Comment by MostHated** [comment]
Well, that was part of the issue. I was not sure how to get the [section] as a variable using this package. The way I ended up doing it was rclone was reading their config using the goconfig package which had a function called GetSectionList() which would return a list of each of the [sections] values as string, then using that list of sections I could use GetSection() which returned a map[string]string of each key/value within the [section], so then I just stored those within a struct. 

It would be much cleaner/nicer to use this package as I could directly get config.String(section.type) (or client_id, etc) but I was not sure how to get the actual [section] data as a variable.

**Comment by inhere** [comment]
OO, Very sorry this library can not meet your needs.

**Comment by MostHated** [comment]
No worries at all. I use this for several other projects and it works awesome. :D  :+1:

**Comment by inhere** [comment]
Thanks you. 
If you just want to use INI for simple config management, You can look at my another library https://github.com/gookit/ini

**Comment by MostHated** [comment]
Oh, interesting, that might do just what I need then. I will have to try it out. Thanks. :+1:
