### ISSUE TITLE
Support Pretty Print?

### ISSUE THREAD

**Issue by KiddoV** [gookit/config#71]
Would be nice to have support for pretty print out-of-the-box like ``Viper``.
Currently: ``config.Set()``
```json
{"parent":{"child":{"grandChild":"Test Val"}}}
```
Expecting:
```json
{
  "parent": {
    "child": {
      "grandChild": "Test Val"
    }
  }
}
```
Is this posible? 
Or any work-around for this?

**Comment by inhere** [comment]
Pretty Print? is config.Export() func ?

**Comment by KiddoV** [comment]
@inhere I meant pretty as JSON for example like above. Like when you export or save config to the file, my JSON would automatically escape newline and indent like ``Viper`` does.

**Comment by KiddoV** [comment]
I found a work-around for this:
```go
func saveConfigToFile(configIns config.Config, configFilePath string) error {
	//Save config file
	buf := new(bytes.Buffer)
	if _, err := configIns.DumpTo(buf, config.JSON); err != nil {
		return fmt.Errorf(err.Error())
	}
	//Pretty print the JSON
	var out bytes.Buffer
	err := json.Indent(&out, buf.Bytes(), "", "    ")
	if err != nil {
		return fmt.Errorf(err.Error())
	}
	ioutil.WriteFile(filepath.Join(configFilePath), out.Bytes(), 0755)
	return nil
}
```
If anyone has a better solution, please share that in this thread!
Thanks,

**Comment by inhere** [comment]
hi @KiddoV  Great.

You can also :

```go
configIns.SetEncoder(config.JSON, func(v interface{}) ([]byte, error) {
    return json.MarshalIndent(v, "", "    ")
})
```
