### ISSUE TITLE
能增加一个配置写入吗？

### ISSUE THREAD

**Issue by 4566704** [gookit/config#73]
现能只能读取，不能写入，建议增加一个写配置
例如 写my.ini

**Comment by inhere** [comment]
`config.Set` 可以更改值， 导出数据到文件：

https://github.com/gookit/config#dump-config-data

**Comment by 4566704** [comment]
导出后，顺序全乱了，注释也没了

**Comment by inhere** [comment]
:) config.data 只存了数据。导出后也只有数据，适用于做数据备份。

**Comment by 4566704** [comment]
明白了，只适合 读取配置文件。没有写入配置文件功能

**Comment by inhere** [comment]
是的。
要保持注释啥的 应该只能用对应的格式库，里面有语法树存注释位置才行。

config 只是做配置数据的读取、合并、管理的。
