### ISSUE TITLE
你好作者,请问之后有没有修改文件后热重载功能的开发计划?

### ISSUE THREAD

**Issue by seed-app** [gookit/config#78]
如上谢谢

**Comment by inhere** [comment]
:) 这个感觉应该是应用去实现。应用监听文件变动然后调用 config 重新 load 文件

**Comment by inhere** [comment]
也可以内置一下，我找个时间加下

**Comment by pya789** [comment]
> 

先用fsnotify监听了（づ￣3￣） 内置更治疗强迫症

**Comment by inhere** [comment]
等我加上再关闭😀

**Comment by pya789** [comment]
> 等我加上再关闭😀

(*￣3￣)╭ 这么肝  fsnotify的event.Op在windows下改变文件属性也会识别成Write而不是Chmod 第一次用Go还没有跑在服务器上 不太清楚是不是平台问题。。。基础太差了我

**Comment by inhere** [comment]
windows 将就用就行了。 可以用WSL 啊，体验也不错

**Comment by pya789** [comment]
> 

电脑卡 不弄那些了(°ー°〃)
