### ISSUE TITLE
`time.Duration`支持从`string`加载

### ISSUE THREAD

**Issue by Charliego93** [gookit/config#81]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/26761592/173542434-9bc9f82e-c4d4-4603-96a5-e31311922d51.png">
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/26761592/173542545-46a6ed90-c708-4974-ac10-4d204cd4ef83.png">

`connMaxIdleTime`和`connMaxLifeTime` 配置为数字 10，加载后为 10ns
<img width="375" alt="image" src="https://user-images.githubusercontent.com/26761592/173542829-1842f5ed-b382-4c34-b65b-1a8eec50b0d4.png">

配置为string `10s` 之后加载panic
<img width="813" alt="image" src="https://user-images.githubusercontent.com/26761592/173543140-48220cbe-dcf8-4720-bf81-ab01f2dadb53.png">

希望可以优化一下？

**Comment by inhere** [comment]
已经添加了。下个版本发

https://github.com/gookit/config/blob/046bdd78d2484736b695743fe2fa1a0edb5f203f/issues_test.go#L168-L201
