### ISSUE TITLE
Support "=", ":", "." characters for default values

### ISSUE THREAD

**Issue by Ridzhi** [gookit/config#9]
```
// config.yml
command: ${APP_COMMAND|app:run}

// main.go
func main() {
    fmt.Println(config.String("command"))
    // Output: ${APP_COMMAND|app:run}
}
```

**Comment by inhere** [comment]
hi @Ridzhi 

now, has been support `: . =` in default value. please see test for more detail:

https://github.com/gookit/config/blob/c56d9e3addc2c0f66e487a4c7dcee76f4312c1ad/read_test.go#L366-L405
