### ISSUE TITLE
hi , 請問在使用yml時 , struct結構體怎給default值?

### ISSUE THREAD

**Issue by zeralux** [gookit/config#94]
hi , 請問在使用yml時 , struct結構體怎給default值?

**Comment by inhere** [comment]
还没支持的，后续可以考虑加个 tag `default:"value"`

**Comment by inhere** [comment]
新版本已经添加此功能:

https://github.com/gookit/config/blob/edd2db667ddf8b1b25dde6fe9a9ed53f70907b32/issues_test.go#L234-L255
